version: '3.4'

services:
  filemanagerapi:
    image: ${DOCKER_REGISTRY-}filemanagerapi
    build:
      context: .
      dockerfile: FileManagerAPI\Dockerfile
  mongo:
    image: mongo
    ports:
      - 27021:27017